insert into companies (id, name, domain) values (1,'Wal-Mart Stores','www.corporate.walmart.com');
insert into companies (id, name, domain) values (2,'Exxon Mobil','www.exxonmobil.com');
insert into companies (id, name, domain) values (3,'Chevron','www.chevron.com');
insert into companies (id, name, domain) values (4,'Berkshire Hathaway','www.berkshirehathaway.com');
insert into companies (id, name, domain) values (5,'Apple','www.apple.com');
insert into companies (id, name, domain) values (6,'Phillips 66','www.phillips66.com');
insert into companies (id, name, domain) values (7,'General Motors','www.gm.com');
insert into companies (id, name, domain) values (8,'Ford Motor','www.ford.com');
insert into companies (id, name, domain) values (9,'General Electric','www.ge.com');
insert into companies (id, name, domain) values (10,'Valero Energy','www.valero.com');
insert into companies (id, name, domain) values (11,'AT&T','www.att.com');
insert into companies (id, name, domain) values (12,'CVS Caremark','info.cvscaremark.com');
insert into companies (id, name, domain) values (13,'Fannie Mae','www.fanniemae.com');
insert into companies (id, name, domain) values (14,'UnitedHealth Group','www.unitedhealthgroup.com');
insert into companies (id, name, domain) values (15,'McKesson','www.mckesson.com');
insert into companies (id, name, domain) values (16,'Verizon Communications','www.verizon.com');
insert into companies (id, name, domain) values (17,'Hewlett-Packard','www.hp.com');
insert into companies (id, name, domain) values (18,'J.P. Morgan Chase & Co.','www.jpmorganchase.com');
insert into companies (id, name, domain) values (19,'Costco Wholesale','www.costco.com');
insert into companies (id, name, domain) values (20,'Express Scripts Holding','www.express-scripts.com');
insert into companies (id, name, domain) values (21,'Bank of America','www.bankofamerica.com');